version: '2.3'
services: 
    yuuki:
        image: "ghcr.io/erisa/emojidumper:latest"
        volumes:
            - type: bind
              source: ./config.yml
              target: /app/config.yml
